node {
   def commit_id
   stage('Preparacion') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }

   stage('ACE deploy') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("ccasill/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }

   stage('Notificar Instana') {
     
     releaseMarker releaseName: "Release ACE 2.3"
   }
}
