node {
   def commit_id
   stage('Preparacion') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       //sh 'npm test'
     }
   }

   stage('Build') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("ccasill/docker-nodejs-demo:latest", '.').push()
     }
   }

   stage('Deploy') {
     sh 'docker stop my-nodejs-app'
     sh 'docker container rm my-nodejs-app'
     sh 'docker pull ccasill/docker-nodejs-demo:latest'
     sh 'docker run -p 3000:3000 -d --name my-nodejs-app ccasill/docker-nodejs-demo:latest'
   }

   stage('Notificar Instana') {
     
     releaseMarker releaseName: "Release demo ${commit_id}"
   }
}
